
###
POST http://localhost:3001/users/signup HTTP/1.1
Content-Type: application/json

{  
    "name": "Sergio Mendoza",
    "email": "sergiomendozap@gmail.com",
    "password": "thetermi",
}

###
POST http://localhost:3001/users/login HTTP/1.1
Content-Type: application/json

{  
    "email": "sergiomendozap@gmail.com",
    "password": "thetermi",
}
###
GET http://localhost:3001/users  HTTP/1.1

# ###
# POST http://localhost:3001/books HTTP/1.1
# Content-Type: application/json

# {
#     "publishDate": "January 12, 1995",
#     "title": "Harry Potter",
#     "author":"Jk rOWLING",
#     "genre": "Fantasy",
#     "description": "Timestamp ctimestamp. This can be handy for recording when a document has been modified or added.",
#     "pageCount": 1500,
#     "price": 6000,
#     "image": "https://vertabelo.com/blog/best-books-for-database-modeling/1.png"
# }
# ###
# PUT http://localhost:3001/books/63c9c27fae19f944212be758 HTTP/1.1
# Content-Type: application/json

# {
#     "publishDate": "January 13, 1995",
#     "title": "Harry Matas",
#     "author":"Jk rOWLING",
#     "genre": "Fantasy",
#     "description": "Timggdgdgstamp ctimestamp. This can be handy for recording when a document has been modified or added.",
#     "pageCount": 150,
#     "price": 30000,
#     "image": "https://vertabelo.com/blog/best-books-for-database-modeling/1.png"
# }

# ###
# DELETE http://localhost:9000/api/users/63c761023c35108cf9aeca46 HTTP/1.1
