###
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "publishDate": "January 15",
    "title": "shawn of the dead",
    "author": "pepito perez",
    "genre": "horror",
    "description": "la calle de su madrettttttttttttttttttttttttttttttttttttretrtretert",
    "pageCount": 312,
    "price":500000,
    "image":"https://vertabelo.com/blog/best-books-for-database-modeling/1.png"
}

